In [1]:
import pandas as pd
from experiment import RollingTestAnalyzer

history_df = pd.read_csv(r"data\power_daily_raw.csv")
SPLIT_RATIO = (7, 1, 2)

# 首个 test target_date 之前的真实历史序列


b_path = r"artifacts\NHITS_no_feat\20260419_133818\rolling_test_raw.csv"
# b_path = r"timellm\short_term_forecast_power_96_7_gpt2_s_TimeLLM_custom_ftS_tilast_eg0_eh64_sl96_ll48_pl7_dm16_nh8_el2_dl1_df32_fc1_ebtimeF_33101_exog_cfg_0-nowaisheng\rolling_test_raw.csv"
# a_path = r"artifacts\LSTM_both_feat\20260416_154832\rolling_test_raw.csv"
# b_path = r"artifacts\LSTM_no_feat\20260417_130738\rolling_test_raw.csv"

# b_path = r"artifacts\PatchTST_no_feat\20260417_130811\rolling_test_raw.csv"

# a = RollingTestAnalyzer(
#     rolling_raw=a_path,
#     full_raw=history_df,
#     split_ratio=SPLIT_RATIO,
# )

b = RollingTestAnalyzer(
    rolling_raw=b_path,
    full_raw=history_df,
    split_ratio=SPLIT_RATIO,
)

# 1. overall 对比
# overall_a = a.overall_metrics()
overall_b = b.overall_metrics()

# 2. horizon-wise 对比（手动看两张表）
# horizon_a = a.loss_matrix("horizon")
horizon_b = b.loss_matrix("horizon")

# 3. window-wise 对比
# window_a = a.loss_matrix("window")
window_b = b.loss_matrix("window")

# A 相对 B 的 window 统计 + win_rate
# summary_a_vs_b = a.loss_summary("window", baseline=b)
summary_b = b.loss_summary("window")

In [2]:
# print(f'a:\n{overall_a}')
print(f'b:\n{overall_b}')

b:
MAE         0.452626
RMSE        0.596669
WAPE(%)     9.306949
Bias       -0.102727
MAPE(%)    10.740301
Name: overall, dtype: float64

In [3]:
# print('horizon_a:')
# horizon_a

In [4]:
print('horizon_b:')
horizon_b

horizon_b:

              MAE      RMSE      Bias
horizon
1        0.208082  0.277860 -0.077296
2        0.293141  0.369548 -0.064823
3        0.393199  0.483934 -0.078483
4        0.458124  0.561636 -0.099276
5        0.543267  0.675511 -0.148089
6        0.599203  0.746069 -0.111795
7        0.673365  0.846027 -0.139325

In [5]:
# print(f'window_a:')
# window_a

In [6]:
print('window_b')
window_b

window_b

                  MAE      RMSE    MAPE(%)
origin_date
2024-11-10   0.182298  0.201151   3.575080
2024-11-11   0.284625  0.346641   6.060957
2024-11-12   0.287557  0.357817   6.137742
2024-11-13   0.241330  0.359294   5.312362
2024-11-14   0.209648  0.400434   4.837862
...               ...       ...        ...
2025-01-31   0.687188  0.828039  20.918835
2025-02-01   0.701514  0.864930  19.474425
2025-02-02   0.772348  0.923451  20.228634
2025-02-03   1.072488  1.202257  26.926787
2025-02-04   1.040224  1.126529  24.875968

[87 rows x 3 columns]

In [7]:
# summary_a_vs_b

In [8]:
summary_b

              mean    median       std   worst10%        max
MAE       0.452626  0.365307  0.268288   0.985944   1.203437
RMSE      0.521100  0.461696  0.290635   1.089300   1.288060
MAPE(%)  10.740301  7.089772  8.358228  28.738602  38.889816