In [ ]:
import pandas as pd
from experiment import RollingTestAnalyzer

history_df = pd.read_csv(r"data\power_daily_raw.csv")
SPLIT_RATIO = (7, 1, 2)

# 首个 test target_date 之前的真实历史序列


b_path = r"rolling_test_raw.csv"
# b_path = r"timellm\short_term_forecast_power_96_7_gpt2_s_TimeLLM_custom_ftS_tilast_eg0_eh64_sl96_ll48_pl7_dm16_nh8_el2_dl1_df32_fc1_ebtimeF_33101_exog_cfg_0-nowaisheng\rolling_test_raw.csv"
# a_path = r"artifacts\LSTM_both_feat\20260416_154832\rolling_test_raw.csv"
# b_path = r"artifacts\LSTM_no_feat\20260417_130738\rolling_test_raw.csv"

# b_path = r"artifacts\PatchTST_no_feat\20260417_130811\rolling_test_raw.csv"

# a = RollingTestAnalyzer(
#     rolling_raw=a_path,
#     full_raw=history_df,
#     split_ratio=SPLIT_RATIO,
# )

b = RollingTestAnalyzer(
    rolling_raw=b_path,
    full_raw=history_df,
    split_ratio=SPLIT_RATIO,
)

# 1. overall 对比
# overall_a = a.overall_metrics()
overall_b = b.overall_metrics()

# 2. horizon-wise 对比（手动看两张表）
# horizon_a = a.loss_matrix("horizon")
horizon_b = b.loss_matrix("horizon")

# 3. window-wise 对比
# window_a = a.loss_matrix("window")
window_b = b.loss_matrix("window")

# A 相对 B 的 window 统计 + win_rate
# summary_a_vs_b = a.loss_summary("window", baseline=b)
summary_b = b.loss_summary("window")

In [2]:
# print(f'a:\n{overall_a}')
print(f'b:\n{overall_b}')

b:
MAE        0.366014
RMSE       0.535888
WAPE(%)    7.526020
Bias       0.058302
MAPE(%)    8.820472
Name: overall, dtype: float64

In [3]:
# print('horizon_a:')
# horizon_a

In [4]:
print('horizon_b:')
horizon_b

horizon_b:

              MAE      RMSE      Bias
horizon
1        0.169556  0.244498  0.019983
2        0.257407  0.346680  0.037405
3        0.325162  0.425332  0.051361
4        0.379032  0.509149  0.061188
5        0.431804  0.590490  0.072383
6        0.471439  0.672637  0.080766
7        0.527697  0.767466  0.085029

In [5]:
# print(f'window_a:')
# window_a

In [6]:
print('window_b')
window_b

window_b

                  MAE      RMSE    MAPE(%)
origin_date
2024-11-10   0.188686  0.215719   3.676486
2024-11-11   0.240864  0.365485   5.327737
2024-11-12   0.252463  0.375313   5.571916
2024-11-13   0.236396  0.394259   5.322351
2024-11-14   0.231776  0.437284   5.339967
...               ...       ...        ...
2025-01-31   0.488255  0.633937  14.560453
2025-02-01   0.662617  0.848366  18.147413
2025-02-02   0.791959  0.968511  20.566992
2025-02-03   0.950199  1.105883  23.496427
2025-02-04   1.148697  1.261663  27.297466

[87 rows x 3 columns]

In [7]:
# summary_a_vs_b

In [8]:
summary_b

             mean    median       std   worst10%        max
MAE      0.366014  0.246375  0.289697   1.033849   1.232969
RMSE     0.435442  0.329341  0.312355   1.140324   1.334476
MAPE(%)  8.820472  5.323257  8.485179  29.113704  35.461169